debug: true
spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
    - jdbc
    - oauth
    - ssl
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        # show_sql: true
        # format_sql: true
        # use_sql_comments: true
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        default-page-size: 10 # 한 페이지에 보여지는 레코드 수
        one-indexed-parameters: true # 요청 파라미터 page의 값이 1부터 시작
  messages:
    basename: messages.validation
    encoding: UTF-8
server:
  port: 8443
  http2:
    enabled: true
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter: DEBUG
decorator:
  datasource:
    p6spy:
      enable-logging: true # 개발 환경에서만 사용