spring:
  config:
    activate:
      on-profile: common
  session:
    store-type: redis # @EnableRedisHttpSession과 같은 효과
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
  data:
    web:
      pageable:
        default-page-size: 10 # 한 페이지에 보여지는 레코드 수
        one-indexed-parameters: true # 요청 파라미터 page의 값이 1부터 시작
  messages:
    basename: messages.validation
    encoding: UTF-8
logging:
  level:
    root: INFO
---
# spring.profiles.group은 spring.config.activate.on-profile과 같은 파일에 있을 수 없음
spring:
  profiles:
    group:
      dev: common, oauth, devdb
      prod: common, oauth, proddb
---
# 현재 활성화할 프로필 그룹을 지정
spring:
  profiles:
    active: dev